source 'https://rubygems.org'
ruby '>= 2.7.6'

gem "rails", "~> 7.0.0"

gem 'bundler'

gem 'listen', '~> 3.1.5'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'pry'

gem 'tzinfo-data', platforms: [:x64_mingw, :mingw, :mswin]