source 'https://rubygems.org'
ruby '>= 2.6.10'

gem 'rails', '5.2.6'

gem 'bundler'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'pry'

gem 'tzinfo-data', platforms: [:x64_mingw, :mingw, :mswin]